### ISSUE TITLE
Exception in compiled release

### ISSUE THREAD

**Issue by large** [nCubed/TheMovieDbWrapper#21]
Hi! I have tested your library for a while and I have  not got the release version to work at all.
Check these error-series:

> Error: 2018.04.17 00:19:18.711 (+02) [5] In HandleAsyncConnection: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at DM.MovieApi.MovieDbFactory.ApiRequestResolver.GetAvailableConstructors(TypeInfo typeInfo) in C:\_dev\github.nCubed\TheMovieDbWrapper\DM.MovieApi\MovieDbFactory.cs:line 179
   at DM.MovieApi.MovieDbFactory.ApiRequestResolver.GetConstructor(Type t) in C:\_dev\github.nCubed\TheMovieDbWrapper\DM.MovieApi\MovieDbFactory.cs:line 153
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at DM.MovieApi.MovieDbFactory.ApiRequestResolver.Get[T]() in C:\_dev\github.nCubed\TheMovieDbWrapper\DM.MovieApi\MovieDbFactory.cs:line 126
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at myapp.myapp_Moviescraper.Query(String sQuery) in C:\Source\myapp\Moviescraper.cs:line 0

My code in Query is this:

        public ArrayList Query(string sQuery)
        {
            var movieApi = MovieDbFactory.Create< IApiMovieRequest >().Value;

            apiSearchResponse = Task.Run(() => {
                return movieApi.SearchByTitleAsync(sQuery);
            }).Result;

            ArrayList pArray = new ArrayList();
            foreach(MovieInfo pMovie in apiSearchResponse.Results)
            {
                DateTime dateTime = pMovie.ReleaseDate;
                pArray.Add(pMovie.OriginalTitle + " (" + dateTime.Year.ToString() + ")");
            }
        return pArray;

This code runs just fine compiled as debug, but crashes as release.
Is this a known problem? Any tips to handle this exception?

Regards. Lars

**Comment by nCubed** [comment]
The wrapper is intended to be used with the async/await pattern. Calling `Task.Run(...).Result` is going to be an issue since there is no awaiting.

Before we dig much deeper into this exception, please read through Stephen Cleary's StackOverflow answer to: [How to call asynchronous method from synchronous method in C#?
](https://stackoverflow.com/questions/9343594/) 

Once you've updated your code with his recommendations, please post back.

**Comment by large** [comment]
Sorry for bothering you with this, the issue was this:
TheMovieDbWrapper.0.8.2' depends on 'Newtonsoft.Json.11.0.2'

So I forgot to copy the Newtonsoft.Json.dll with the installerpackage.

Regarding the async/await pattern, I have read this post before and the solution B is related for my app, since it is a windows service; no GUI messagequeue.

I created several tests for trying to make it dead-lock, but it works like a rock 👍

**Comment by nCubed** [comment]
Glad it was just a missing dll.

Regarding "solution B", you'll still need an awaitable. The solution Stephen posted is using his own [AsyncContext utility](https://github.com/StephenCleary/AsyncEx/wiki/AsyncContext) You may want to check again since the code posted is not using his `AsyncContext`.
